# Primer paso, extraer los datos de un archivo CSV.

In [3]:
import pandas as pd
extracted_data = pd.read_csv("conjunto_de_datos_iter_00CSV20.csv")

/var/folders/ck/pg7bynv56nsdnxf0f007y0lc0000gn/T/ipykernel_86586/854634524.py:2: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  extracted_data = pd.read_csv("conjunto_de_datos_iter_00CSV20.csv")

# Verificar el contenido.

In [4]:
extracted_data.head()

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,LOC,NOM_LOC,LONGITUD,LATITUD,ALTITUD,POBTOT,...,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCINT,VPH_SINTIC,TAMLOC
0,0,Total nacional,0,Total nacional,0,Total nacional,NaN,NaN,NaN,126014024,...,30775898,18307193,15211306,6616141,4047100,1788552,3170894,15108204,852871,*
1,0,Total nacional,0,Total nacional,9998,Localidades de una vivienda,NaN,NaN,NaN,250354,...,47005,8385,18981,1732,1113,12775,14143,51293,7154,*
2,0,Total nacional,0,Total nacional,9999,Localidades de dos viviendas,NaN,NaN,NaN,147125,...,25581,5027,11306,971,708,8247,10065,29741,5283,*
3,1,Aguascalientes,0,Total de la entidad Aguascalientes,0,Total de la Entidad,NaN,NaN,NaN,1425607,...,359895,236003,174089,98724,70126,6021,15323,128996,1711,*
4,1,Aguascalientes,0,Total de la entidad Aguascalientes,9998,Localidades de una vivienda,NaN,NaN,NaN,3697,...,732,205,212,48,41,39,62,530,20,*

# Transformar datos

In [12]:
def tranform(data_frame, value):
    return data_frame.loc[data_frame["NOM_ENT"] == value, ["ENTIDAD","NOM_ENT","LOC","POBTOT","POBFEM","POBMAS"]]
transformed_data = tranform(data_frame=extracted_data,value="Sinaloa" )

In [13]:
transformed_data.head()

        ENTIDAD  NOM_ENT   LOC   POBTOT   POBFEM   POBMAS
144314       25  Sinaloa     0  3026943  1532128  1494815
144315       25  Sinaloa  9998    20358     8853    11505
144316       25  Sinaloa  9999     6701     2062     4639
144317       25  Sinaloa     0   459310   233994   225316
144318       25  Sinaloa     1   298009   154344   143665

# Cargar datos.

In [15]:
def load(data_frame,filename):
    return data_frame.to_csv(filename)
load(data_frame=transformed_data,filename="cleaned_data.csv")